pipeline:
  test:
    image: node:12.13.0-stretch-slim
    commands:
      - node -v
      - npm -v
      - npm install

  build:
    image: node:12.13.0-stretch-slim
    commands:
      - npm run build
    when:
      branch:
        - master
      event:
        - push

  docker_publish:
    image: plugins/docker
    repo: goharbor.erxes.io/${DRONE_REPO_OWNER}/${DRONE_REPO_NAME}
    registry: goharbor.erxes.io
    dockerfile: Dockerfile
    secrets:
      - docker_username
      - docker_password
    tags:
      - ${DRONE_BRANCH}
    when:
      branch:
        - master
      event:
        - push
